# -*- coding: utf-8 -*-

###########################################################
# PyToxo
#
# A Python library for calculating penetrance tables of any
# bivariate epistasis model.
#
# Copyright 2021 Borja González Seoane
#
# Contact: borja.gseoane@udc.es
###########################################################

"""PyToxo model unit test suite."""

import os
import unittest

import pytoxo.errors
import pytoxo.model


class GAMETESFormatTestSuite(unittest.TestCase):
    """Tests for check to correct composition of the `PTable` formatted as
    GAMETES format.
    """

    def test_ptable_format_as_gametes(self):
        """Test composition of the `PTable` formatted as GAMETES format,
        comparing with the table generated by Toxo to the same input."""
        m = pytoxo.model.Model(os.path.join("models", "additive_2.csv"))
        p = m.find_max_prevalence_table(mafs=[0.25] * m.order, h=0.2, check=False)

        # Toxo contrast
        expected_output = (
            "Attribute names:	P0	P1"
            + "Minor allele frequencies:	0.250	0.250"
            + "x: 0.09717040"
            + "y: 0.79108624"
            + "Prevalence: 0.20000000"
            + "Heritability: 0.09238291"
            + ""
            + "Table:"
            + ""
            + "0.09717040, 0.17404057, 0.31172168"
            + "0.17404057, 0.31172168, 0.55832041"
            + "0.31172168, 0.55832041, 1.00000000"
            + ""
        )

        output = p._compound_table_as_gametes()
        self.assertEqual(expected_output, output)
